/* ======= MODELS DATA ======= */
const MODELS = [
  { id:'auto', name:'Smart Router', provider:'Kombat AI', desc:'Auto-selects the best model for your task', icon:'🧠', color:'#6366f1', inputCost:0, outputCost:0, ctx:'Varies', speed:'Optimized', strengths:['Cost optimization','Best model matching','Learns your preferences'] },
  { id:'gpt-4o', name:'GPT-4o', provider:'OpenAI', desc:'Great all-rounder for coding, analysis, and creative tasks', icon:'✦', color:'#10a37f', inputCost:2.5, outputCost:10.0, ctx:'128K', speed:'Fast', strengths:['Coding','Analysis','Following instructions'] },
  { id:'gpt-4o-mini', name:'GPT-4o Mini', provider:'OpenAI', desc:'Fast and affordable for everyday tasks', icon:'✦', color:'#10a37f', inputCost:0.15, outputCost:0.6, ctx:'128K', speed:'Very Fast', strengths:['Speed','Cost-effective','Simple tasks'] },
  { id:'claude-sonnet', name:'Claude Sonnet 4', provider:'Anthropic', desc:'Excellent for nuanced writing, analysis, and reasoning', icon:'◈', color:'#d97706', inputCost:3.0, outputCost:15.0, ctx:'200K', speed:'Fast', strengths:['Creative writing','Reasoning','Long documents'] },
  { id:'claude-haiku', name:'Claude Haiku', provider:'Anthropic', desc:'Quick and cost-effective for simple tasks', icon:'◈', color:'#d97706', inputCost:0.25, outputCost:1.25, ctx:'200K', speed:'Very Fast', strengths:['Speed','Summarization','Classification'] },
  { id:'gemini-pro', name:'Gemini 2.5 Pro', provider:'Google', desc:'Powerful multimodal model with massive context', icon:'◆', color:'#4285f4', inputCost:1.25, outputCost:10.0, ctx:'1M', speed:'Fast', strengths:['Multimodal','Long context','Research'] },
  { id:'gemini-flash', name:'Gemini 2.5 Flash', provider:'Google', desc:'Ultra-fast and budget-friendly', icon:'◆', color:'#4285f4', inputCost:0.15, outputCost:0.6, ctx:'1M', speed:'Fastest', strengths:['Speed','Budget','Bulk tasks'] },
  { id:'llama-4', name:'Llama 4 Maverick', provider:'Meta', desc:'Open-source powerhouse for diverse tasks', icon:'🦙', color:'#7c3aed', inputCost:0.2, outputCost:0.6, ctx:'128K', speed:'Fast', strengths:['Open source','Multilingual','Coding'] },
  { id:'deepseek-v3', name:'DeepSeek V3', provider:'DeepSeek', desc:'Ultra-affordable coding specialist', icon:'🔮', color:'#06b6d4', inputCost:0.14, outputCost:0.28, ctx:'128K', speed:'Fast', strengths:['Coding','Math','Ultra-cheap'] },
  { id:'mistral-large', name:'Mistral Large', provider:'Mistral', desc:'European AI with strong multilingual support', icon:'▲', color:'#f97316', inputCost:2.0, outputCost:6.0, ctx:'128K', speed:'Fast', strengths:['Multilingual','EU compliance','Reasoning'] },
];

const MODEL_MAP = {};
MODELS.forEach(m => MODEL_MAP[m.id] = m);

const SAMPLE_RESPONSES = {
  'gpt-4o': "Great question! Let me break this down for you step by step.\n\n**Analysis:**\nBased on current market trends and data analysis, here are the key insights:\n\n1. **Market Growth** — The AI industry is projected to reach $1.8 trillion by 2030\n2. **Key Players** — OpenAI, Anthropic, Google, and Meta are leading the charge\n3. **Opportunities** — SaaS platforms that aggregate AI capabilities are seeing 300% YoY growth\n\n*Would you like me to dive deeper into any of these areas?*",
  'claude-sonnet': "I'd be happy to help you explore this topic in depth.\n\nLet me share a nuanced perspective on this:\n\nThe landscape of AI agents is fascinating because it represents a fundamental shift from **tools** to **collaborators**. Here's what I find particularly compelling:\n\n• **Autonomy vs Control** — The best agent systems give users transparency into decisions while handling complexity behind the scenes\n• **Multi-model orchestration** — Rather than one model doing everything, specialized models working together produce superior results\n• **Cost optimization** — Smart routing between models can reduce API costs by 60-80% without sacrificing quality\n\nShall I elaborate on any of these points?",
  'gemini-pro': "Here's a comprehensive analysis based on my research:\n\n## Key Findings\n\nAfter analyzing multiple data sources, I've identified several important trends:\n\n📊 **Data Point 1**: Multi-LLM platforms are growing 4x faster than single-model solutions\n📊 **Data Point 2**: Users who compare model outputs report 40% higher satisfaction\n📊 **Data Point 3**: Auto-routing can save businesses an average of $2,400/year on API costs\n\n### Recommendations\n\n- Smart routing → High impact, medium effort\n- Model comparison → High impact, low effort\n- Cost dashboard → Medium impact, low effort\n\nWould you like me to create a detailed action plan based on these findings?",
  'llama-4': "Sure! Here's my take on this:\n\nAs an open-source model, I bring a unique perspective. The key advantage of multi-model platforms is **flexibility and cost control**.\n\nHere are my recommendations:\n\n1. Start with cheaper models for simple tasks\n2. Route complex reasoning to premium models\n3. Use open-source models (like me!) for privacy-sensitive tasks\n4. Always give users the option to choose\n\nThe future of AI isn't about one model winning — it's about the right model for the right task. 🦙",
  'deepseek-v3': "```python\n# Here's an optimized implementation for your use case\n\nclass SmartRouter:\n    def __init__(self, models):\n        self.models = models\n        self.performance_history = {}\n    \n    def select_model(self, task):\n        \"\"\"Auto-select the best model based on task type.\"\"\"\n        task_type = self._classify_task(task)\n        \n        routing_table = {\n            'coding': 'deepseek-v3',\n            'creative': 'claude-sonnet', \n            'analysis': 'gemini-pro',\n            'general': 'gpt-4o-mini',\n        }\n        \n        return routing_table.get(task_type, 'gpt-4o-mini')\n```\n\nThis implementation uses a simple routing table, but you could extend it with ML-based classification for better accuracy.",
  'mistral-large': "Excellent question! Let me provide a well-structured analysis.\n\n**Executive Summary:**\nThe multi-LLM approach offers three distinct advantages:\n\n🔹 **Resilience** — No single point of failure; if one provider is down, others take over\n🔹 **Optimization** — Match task complexity to model capability and cost\n🔹 **Innovation** — Instantly adopt new models as they're released\n\n**Market Context:**\nEuropean businesses particularly value this approach due to data sovereignty requirements.\n\nWould you like me to compare specific models for your use case?",
  'gpt-4o-mini': "Here's a quick summary:\n\n• AI aggregation platforms are becoming the standard for businesses\n• Smart model routing is a proven cost-saver\n• Multi-model access provides flexibility and redundancy\n\nKey takeaway: Start with a focused MVP and iterate based on user feedback!",
  'claude-haiku': "Quick summary:\n\n1. Multi-LLM platforms = growing demand\n2. Smart routing = significant cost savings\n3. Side-by-side comparison = user trust builder\n4. BYOK model = removes adoption barriers\n\nBottom line: Strong market opportunity with clear differentiation paths.",
  'gemini-flash': "Fast answer:\n\n📌 Multi-model AI platforms are trending up\n📌 Smart routing saves 60-80% on API costs\n📌 Battle mode builds user engagement\n📌 India-first pricing captures huge underserved market\n\nRecommendation: Build MVP with these 4 core features.",
};

const TASK_CATEGORIES = [
  { id:'coding', label:'Coding', icon:'💻', bestModel:'deepseek-v3', keywords:['code','program','function','bug','debug','python','javascript','api','implement','build','develop'] },
  { id:'creative', label:'Creative Writing', icon:'✍️', bestModel:'claude-sonnet', keywords:['write','story','poem','creative','blog','article','copy','tone','narrative','essay'] },
  { id:'analysis', label:'Analysis', icon:'📊', bestModel:'gemini-pro', keywords:['analyze','research','data','compare','trend','report','study','statistics','market'] },
  { id:'math', label:'Math & Logic', icon:'🔢', bestModel:'deepseek-v3', keywords:['math','calculate','equation','solve','proof','formula','algorithm'] },
  { id:'general', label:'General', icon:'💬', bestModel:'gpt-4o-mini', keywords:['explain','help','what','how','tell','describe','list','suggest'] },
  { id:'translation', label:'Translation', icon:'🌐', bestModel:'mistral-large', keywords:['translate','language','hindi','spanish','french','german','japanese','chinese'] },
  { id:'summarize', label:'Summarize', icon:'📝', bestModel:'claude-haiku', keywords:['summarize','summary','brief','tldr','key points','condense','shorten'] },
];
